[project]
name = "dr-robotnik-ring-racers-addons-manager"
version = "1.1"
description = "Ring racers/SRB2Kart Addons Manager"
authors = [
    { name="Ton Nom", email="ton.email@example.com" }
]

requires-python = ">=3.10.5"

dependencies = [
    "pyinstaller==6.15.0"
]
