[project]
name = "dr-robotnik-ring-racers-addons-manager"
version = "1.2"
description = "Ring Racers/SRB2Kart Addons Manager"
authors = [
    { name="Sanghelyos", url="https://github.com/Sanghelyos" }
]

requires-python = ">=3.10.5"

dependencies = [
    "pyinstaller==6.15.0"
]
